name: CD
on:
  create:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  issues: write    # for create-issue job
  contents: read   # for build-and-deploy job
  packages: write  # for build-and-deploy job

jobs:
  create-issue:
    name: Create deploy tracking issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v4
      with:
        script: |
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `${context.ref} (${context.sha}) being deployed`,
              body: `ref: ${context.ref}\nsha: ${context.sha}\nactor: ${context.actor}\nevent:${context.eventName}`,
            })

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: hashtagchris
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
          registry: ghcr.io
          username: hashtagchris
          password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hashtagchris/binary-json-formatter-fork:latest
            ghcr.io/hashtagchris/binary-json-formatter-fork:latest
