name: CD
on:
  create:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  issues: write    # for create-issue job
  contents: read   # for build-and-deploy job

jobs:
  create-issue:
    name: Create deploy tracking issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v5
      with:
        script: |
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `${context.ref} (${context.sha}) being deployed`,
              body: `ref: ${context.ref}\nsha: ${context.sha}\nactor: ${context.actor}\nevent:${context.eventName}`,
            })

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: hashtagchris
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
        repository: hashtagchris/binary-json-formatter-fork
        tags: latest
        
