name: context
on:
  create:
  push:
  pull_request:
  workflow_dispatch:
  deployment:  # triggered by secrets.yml, which uses `environment`
  deployment_status:
  issue_comment:
  registry_package:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_ACTOR triggered $GITHUB_EVENT_NAME"
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_SHA
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v2.4.0
