name: issue_comment
on:
  issue_comment:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo ${{ github.event.issue.number }}
      - uses: actions/checkout@v2.4.0
        with:
          ref: "refs/pulls/${{ github.event.issue.number }}/merge"
